# Generated by Django 4.2.5 on 2024-02-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_customuser_phone_number_alter_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.TextField(default='', max_length=150),
        ),
    ]
