# Generated by Django 4.2.5 on 2024-04-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_course_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=25)),
                ('description', models.TextField(default='', max_length=150)),
            ],
            options={
                'verbose_name': 'Announcement and Update',
                'verbose_name_plural': 'Announcements and Updates',
            },
        ),
    ]
