# Generated by Django 4.2.5 on 2024-04-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='description',
            field=models.TextField(default='', max_length=300),
        ),
    ]
