# Generated by Django 4.2.5 on 2024-04-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_chapter_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='thumbnail/'),
        ),
    ]
